Feat/create header component
OpenDevUFCG/roadmap-cc pull request #192
Opened 2022-09-17 19:30 UTC by franklingg

#### Issue

closes #182 

#### Qual o objetivo dessa Pull Request?

Criar o componente Header. Além disso, permite alterar as línguas para inglês e espanhol.

#### Como pode ser manualmente testado?

É preciso rodar `yarn ou npm install` por ter novas dependências (`react-select` e `babel`), antes de rodar `yarn dev`

2022-09-17 20:49 UTC, NicolasLopes7 commented on src/components/Header/index.jsx
> +        </a>
o componente a foi usado para dar só para dar o cursor pointer? acho que seria mais interessante criar uma classe e atribuir no componente `Link`

2022-09-17 20:50 UTC, NicolasLopes7 commented on src/components/Header/index.jsx
> +        </Link>
Da mesma forma podemos passar a classe diretamente para o componente Link

2022-09-17 20:51 UTC, NicolasLopes7 commented on src/components/Header/index.jsx
> +          <a className={router.pathname === '/home' ? 'nav-checked' : undefined}>{t('nav.home')}</a>
`{router.pathname === '/home' ? 'nav-checked' : undefined}` isso aqui pode ser abstraído para uma função para facilitar a leitura

sugestão: 
```js
const getClassByRouteName = (routeName) => router.pathname === routeName ? 'nav-checked' : null
```

2022-09-17 20:54 UTC, NicolasLopes7 commented on src/components/Header/index.jsx
> +        </Link>
Talvez um componente SocialMedia dentro da propria pasta de header? Ficaria melhor para a leitura e evitaria ter muito [css aninhado dentro do componente pai](https://github.com/OpenDevUFCG/roadmap-cc/pull/192/files#diff-ac68d0c86d0ae8e9e090d032b01fbb13a6dd1c90c832c122559a7b460dc927abR43-R51).

2022-09-17 20:54 UTC, NicolasLopes7 commented on src/components/Header/styles.jsx
> +        }
Acho que criar componentes menores e evitar aninhamento de css pode ser uma boa..A medida que o código cresce css aninhado começa a ser bem confuso

2022-09-17 20:57 UTC, NicolasLopes7 commented on src/components/Header/styles.jsx
> +`
Talvez usar uma lib mais opinada para componentes? Parece bastante customização para um select simples..tinha puxado uma discussão sobre isso nesse [PR](https://github.com/OpenDevUFCG/roadmap-cc/issues/186#issuecomment-1250130654) e no [discord](https://discord.com/channels/558293573494112257/558367503030681608/1020794982208110714)

2022-09-17 20:57 UTC, NicolasLopes7 commented on src/i18n/index.js
> +import { initReactI18next,  } from 'react-i18next';
```suggestion
import { initReactI18next } from 'react-i18next';
```

2022-09-17 21:03 UTC, NicolasLopes7 commented
<img width="872" alt="Screen Shot 2022-09-17 at 23 00 59" src="https://user-images.githubusercontent.com/57234795/190876298-5e7cea8d-9f1e-4aaf-a89d-4cb6aefe11eb.png">
Acho que também poderia adicionar uma media query para converter os ícones de redes sociais para um `hamburger menu`. talvez definir alguma outra forma para o tamanho das fotos ajude a não distorcer

2022-09-17 23:39 UTC, RodrigoEC commented
> <img alt="Screen Shot 2022-09-17 at 23 00 59" width="872" src="https://user-images.githubusercontent.com/57234795/190876298-5e7cea8d-9f1e-4aaf-a89d-4cb6aefe11eb.png">
> 
> Acho que também poderia adicionar uma media query para converter os ícones de redes sociais para um `hamburger menu`. talvez definir alguma outra forma para o tamanho das fotos ajude a não distorcer

@franklingg e @NicolasLopes7 Gente tinha esquecido de fazer o design do mobile, aí fiz aqui:

![image](https://user-images.githubusercontent.com/42751604/190879731-70f8417f-c32c-4b2e-b377-738272800634.png)

Tanto o footer como o header tem conteúdos que são repetidos retirados, já que eles não eram estritamente necessários

2022-09-18 15:48 UTC, franklingg commented on src/components/Header/index.jsx
> +        </a>
Em next o componente Link é usado apenas como uma interface pra âncora, ele não é renderizado e na página fica apenas o `a`, por isso é preciso ter os dois juntos

2022-09-18 15:50 UTC, franklingg commented on src/components/Header/index.jsx
> +        </Link>
Como disse lá em cima, na renderização teria apenas a âncora com a imagem dentro, o que é bem comum.

2022-09-18 15:57 UTC, franklingg commented on src/components/Header/styles.jsx
> +        }
O componente já é bem pequeno, e dificilmente vai expandir mais (já que é só um header, não tem mais o que crescer absurdamente). O benefício de usar css aninhado é o de evitar criar classes demais e fazer ajustes de instância, etc.

2022-09-18 16:00 UTC, franklingg commented on src/components/Header/styles.jsx
> +`
Ai dependeria de outras opiniões (alô @LeandraOS , @RodrigoEC )
No meu ver não parece algo exorbitantemente grande, já que o design desse select pedia bastante customização (até nos itens da lista ao abrir). E também não sabemos os futuros `selects`, pode ser que mais customização ainda seja necessária.

2022-09-25 00:34 UTC, LeandraOS commented on src/components/Header/styles.jsx
> +            transform: scale(1.05);
Acredito que seria muito legal aplicar esse efeito de transform nos ícones abaixo:
![Captura de tela de 2022-09-24 21-21-36](https://user-images.githubusercontent.com/50140771/192123186-077c64bd-9349-4708-b12e-652414aa1137.png)
para o hover dos links é legal ser a cor #FC8E51. O que achas @franklingg?

2022-09-25 00:34 UTC, LeandraOS commented on src/components/Header/styles.jsx
> +    @media (max-width: 428px){
Nas medidas abaixo de 375px, estamos com a responsividade assim, seria legal corrigir esse detalhe 
![Captura de tela de 2022-09-24 21-18-20](https://user-images.githubusercontent.com/50140771/192123331-34d1351b-8174-4b61-82e5-7d6ad0085d67.png)

2022-09-25 01:16 UTC, LeandraOS commented
@franklingg por favor, faz um` git pull origin develop` pra a tua branch porque temos atualizações na develop.

2022-10-10 04:48 UTC, LeandraOS requested changes

2022-10-10 04:48 UTC, LeandraOS commented on src/styles/globals.css
> +  background: url("../assets/img/background.png") repeat;
Ooie @franklingg aqui temos a falta da chave de fechamento do `body` peço que adicione por favorzinho :rocket: 
![Captura de tela de 2022-10-10 01-45-42](https://user-images.githubusercontent.com/50140771/194800489-903e8462-7183-4649-aca9-163f1764bac1.png)

2022-10-10 04:48 UTC, LeandraOS commented on src/i18n/index.js
> +import translationsESES from './locales/es-es.json';
Nessa linha, temos um pequeno detalhe de digitação do path do arquivo. Ele apresenta o seguinte erro: 

![Captura de tela de 2022-10-10 01-47-07](https://user-images.githubusercontent.com/50140771/194800571-f092faa1-6b40-4b64-8b45-eca0fa967ddd.png)

Para resolver, basta alterar o `es-es.json` para `es-ES.json`

`import translationsESES from './locales/es-ES.json';`

2022-10-15 04:28 UTC, LeandraOS requested changes

2022-10-15 04:28 UTC, LeandraOS commented on src/components/Header/index.jsx
> +        <Link href="https://www.instagram.com/opendevufcg/" prefetch={false}>
Oooie @franklingg se possível tem como você alterar essa url? Ao clicar no ícone do opencollective ele tá me redirecionando para o instagram. Esse é o link do opencollective da OpenDev: https://opencollective.com/opendevufcg :rocket:

2022-10-15 04:28 UTC, LeandraOS commented on src/components/Header/index.jsx
> +        <Link href="https://www.instagram.com/opendevufcg/" prefetch={false}>
@franklingg se possível tem como você alterar essa url? Ao clicar no ícone do nosso discord ele tá me redirecionando para o instagram. Esse é o link do discord da OpenDev:https://discord.gg/jSFq7XyGe3 :rocket:

2022-10-16 19:42 UTC, closed without merging